apiVersion: v2
name: hsr
version: v0.1.32
description: Honkai Starrail official website Helm chart
type: application
sources:
  - https://github.com/Peerapon966/hsr
maintainers:
  - name: Peerapon966
    url: https://github.com/Peerapon966
appVersion: "v0.0.1"
